#Written by Sergio Padure for IT-Anywhere
version: "3.4"
volumes:
  centreonpoller-etc:
  centreonpoller-cache:
  centreonpoller-lib:
services:
    centreon:
        env_file: .env
        image: "itanywhere/ita-centreonpoller-20-10:development"
        entrypoint:
            - /root/entrypoint.sh
        container_name: centreon_poller
        hostname: ${HOSTNAME}
        domainname: ${DOMAINNAME}
        restart: on-failure
        volumes:
            - centreonpoller-etc:/etc
            - centreonpoller-cache:/var/cache
            - centreonpoller-lib:/var/lib/
        environment:
            - PRIVKEY=${PRIVKEY}
            - POLLERID=${POLLERID}
            - TIMEZONE=${TIMEZONE}
            - TZ=${TZTIME}
        ports:
            - "5550-5560:5550-5560"
